spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sgpc
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml